currentFS: int = 0  # [ANNOTATION] Add type annotations to all state variables so static analysis catches misassignments.
image_option: int = 0  # [ANNOTATION] Add type annotation.
partition_scheme: int = 0  # [ANNOTATION] Add type annotation.
target_system: int = 0  # [ANNOTATION] Add type annotation.
cluster_size: int = 0  # [ANNOTATION] Add type annotation.
QF: int = 0  # [ANNOTATION] Add type annotation.
create_extended: int = 0  # [ANNOTATION] Add type annotation.
check_bad: int = 0  # [ANNOTATION] Add type annotation.
new_label: str = "USB_DRIVE"  # [ANNOTATION] Shorten default from "Volume Label" (12 chars) to "USB_DRIVE" (9 chars); FAT32 labels are limited to 11 characters.
iso_path: str = ""  # [ANNOTATION] Add type annotation (was already annotated; kept for consistency).
DN: str = ""  # [ANNOTATION] Add type annotation.
currentflash: int = 0  # [ANNOTATION] Add type annotation.
language: str = "English"  # [ANNOTATION] Add type annotation.
verify_hash: bool = False  # [ANNOTATION] Add type annotation.
expected_hash: str = ""  # [ANNOTATION] Add type annotation.
